name: Build Docker images
on:
  pull_request:
    branches:
      - main
jobs:
  build-docker-images:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Build images using docker compose
      run: docker-compose up -d
