services:
  app:
    build: app
    volumes:
      - data:/data

  haproxy:
    build: haproxy
    ports:
      - "80:80" # used for ssl certificate renewal
      - "443:443"
    volumes:
      - certs:/certs

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./certs
  letsencrypt:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /etc/letsencrypt

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
