data_folder = "/data/"
data_uptimerobot_folder = "/data_uptimerobot/"
db_file = f"{data_folder}meteo.db"
run_emergency = f"{data_folder}run_emergency"
run_emergency_failed = f"{data_folder}run_emergency_failed"
last_updated = f"{data_folder}last_updated"
editdist_extension = "/sqlite_extensions/fuzzy.so"
