name: Check HAProxy Config
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install HAProxy
        run: sudo apt-get update && sudo apt-get install -y haproxy
      - name: Check HAProxy Config
        run: haproxy -c -f haproxy/haproxy.cfg
