name: Check HAProxy Config
on: [pull_request]
jobs:
  check-haproxy-config:
    #if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install HAProxy # I want 3.0.7, looks like I can only get 2.8.5 on ubuntu at the moment
        run: sudo apt-get update && sudo apt-get install -y haproxy
      - name: Fix binding before check
        run: |
          grep -q "app:8000" haproxy/haproxy.cfg &&\
          sed -i "s~app:8000~localhost:8000~" haproxy/haproxy.cfg
      - name: Fix ssl before check
        run: |
          grep -q "bind :443 ssl" haproxy/haproxy.cfg &&\
          sed -i "s~bind :443 ssl~bind :443 \#ssl~" haproxy/haproxy.cfg
      - name: Check HAProxy Config
        run: |
          haproxy -c -f haproxy/haproxy.cfg
